version: '3'

networks:
  den-network:
    driver: bridge

services:

        den:
            container_name: den
            build:
                context: ./php-fpm
                args:
                    - timezone=${TZ}
            networks:
                - den-network
            ports:
                - "900:9000"
            volumes:
                - ./../den:/den:rw,cached
                - den_log:/den/var/log
            env_file:
                - .env
            depends_on:
                - redis
                - memcached
                - db-master

        nginx:
            container_name: nginx
            build:
                context: ./nginx
                args:
                    - timezone=${TZ}
            ports:
                - "81:80"
                - "443:443"
            networks:
                - den-network
            depends_on:
                - den
            volumes:
                - ./../den/public:/den/public
                - ./nginx/ssl:/etc/nginx/ssl
                - ./nginx/conf.d:/etc/nginx/conf.d
                - ./nginx/nginx_log:/var/log/nginx
                - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            env_file:
                - .env
            command: /bin/bash -c "exec nginx -g 'daemon off;'"

        redis:
            container_name: redis
            image: redis:latest

            networks:
                - den-network

        memcached:
            container_name: memcached
            image: memcached:latest
            networks:
                - den-network


        db-master:
            container_name: db-master
            image: mysql:latest
            env_file:
                - ./db/master/.env.master
            ports:
                - "4406:3306"
            volumes:
                - ./db/master/master.sql:/docker-entrypoint-initdb.d/start.sql
                - ./db/master/mysql.master.cnf:/etc/mysql/conf.d/mysql.master.cnf
                - ./db/master/.data/mysql:/var/lib/mysql:rw
            networks:
                - den-network

volumes:
    nginx_log:
    den_log:
    db:
        driver: local

